### ISSUE TITLE
Method that returns the objectValuesContainer?

### ISSUE THREAD

**Issue by martinxsliu** [airshiphq/airship-go#5]
The Go client currently has to make separate HTTP requests for each single piece of data (eligible, enabled, treatment, payload) when the microservice actually returns the entire set of data in its response. This means that we are wasting resources making redundant requests. Granted, the microservice should be hosted within our network so the cost is smaller, but it still incurs overhead and has a chance of failure.

How do you feel about the client instead having a single method that returns an exported `objectValuesContainer` struct? Perhaps call it something like `Variant` to make it more user friendly?

**Comment by glusa8** [comment]
If the sequence of calls try to retrieve the different values (eligible, enabled, treatment, payload) for the same (flag, entity) pair, then we may be able to use a small cache with expiration time to cache the result.

Changing the interface would mean we have to do it in other SDKs to maintain consistency, and that's something we have to think about.

**Comment by martinxsliu** [comment]
Yes, totally understand the desire for a single consistent API across SDKs. Would introducing a single new method that returns the combined data, while keeping the existing interface, be more palatable? Either way, it would be desirable to not have to incur this cost.

**Comment by glusa8** [comment]
@martinxsliu yes, that would be more palatable. Thanks for understanding.

**Comment by glusa8** [comment]
@martinxsliu , I implemented `ObjectValuesContainer`, but this repo is now deprecated in favor of

`https://github.com/airshiphq/flagger-go`

I'm closing the issue here, but going forward, could you use `flagger`? That is the new name of our Go SDK going forward.
